name: Deploy to GitHub Pages

on:
    push:
        branches: ["main"]

permissions:
    contents: read
    pages: write # Required to deploy to Pages
    id-token: write # Required for authentication

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: "24"
                  cache: "yarn"

            - name: Install dependencies
              run: yarn install --immutable

            - name: Setup Pages
              uses: actions/configure-pages@v4

            - name: Prep secrets
              run: |
                  mkdir -p auth
                  echo "${{ secrets.R2_B64 }}" | base64 -d > auth/r2.json
                  echo "${{ secrets.SERVICE_WORKER_B64 }}" | base64 -d > auth/service-worker.json

            - name: Update images
              run: yarn tsx scripts/updateImages.ts ${DRIVE_URL}

            - name: Build
              run: yarn build

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "./dist"

    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
